### ISSUE TITLE
shuffle config doesn't take a boolean but a String

### ISSUE THREAD

**Issue by maxdhn** [rewish/jquery-bgswitcher#1]
$('body').bgswitcher({
                images: ["style/img/0.jpg","style/img/1.jpg","style/img/3.jpg","style/img/4.jpg"],
                effect: "fade",
                shuffle: "false",
                interval: 5000
            });

**Comment by rewish** [comment]
Will you give me an example code?

**Comment by rewish** [comment]
Why do you specify a string?

**Comment by maxdhn** [comment]
I'm sorry, I made a mistake by reading the documentation...I'm very sorry.
