### ISSUE TITLE
Stretching images?

### ISSUE THREAD

**Issue by perthsystem** [rewish/jquery-bgswitcher#14]
Hi, great plugin :)

I have noticed that the images are repeated on the page, is there an option to stretch the image to fit the page?

Thank you,
John

**Comment by perthsystem** [comment]
I worked it out, using CSS - looks great now :)

**Comment by rewish** [comment]
So good :)

**Comment by hourdays** [comment]
@perthsystem, would you please be so kind as to share your CSS solution ? I'm using this awesome plugin to fade body background image but indeed it is repeated.

**Comment by hourdays** [comment]
My bad got it to work with background-size: cover.
