### ISSUE TITLE
Background repeats and spills

### ISSUE THREAD

**Issue by cattalk** [rewish/jquery-bgswitcher#16]
Hello,

Thanks for this plugin!

I have a problem: Sometimes when loading a page with bgswitcher the images are repeated and spill oust of the container. I've noticed that the div style property contains "repeat". Is there a possibility to make it not repeating? 
This happens with Safari, Chrome, FF, IE under os x and win. When reloading the page it usually does not happen. 
Do you have a suggestion what I could do?

Thank you!
cat

**Comment by rewish** [comment]
Hi,
Have you tried `background-repeat: no-repeat;`?

**Comment by rewish** [comment]
@cattalk, did you solve the problem?

**Comment by parkerjohn** [comment]
I am having the same issue, background repeats on Android. I am not sure how to change the css as you suggest as there is no id or class on the created div.
