### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by Aohor** [rewish/jquery-bgswitcher#17]
How to make the images responsive?

**Comment by Jonathlee** [comment]
Use CSS = Background-size: cover / contain

**Comment by rewish** [comment]
@Aohor, did you solve the problem?

**Comment by Aohor** [comment]
actually I didn't try. using another plugin.

**Comment by rewish** [comment]
Okay, I'll close it.

**Comment by crecorn** [comment]
Where does this go to make it responsive?

"CSS = Background-size: cover / contain"
