### ISSUE TITLE
background-colorの指定

### ISSUE THREAD

**Issue by trickstar13** [rewish/jquery-bgswitcher#18]
&lt;div id="test"&gt;
&lt;div class="box"&gt;
&lt;p&gt;Lorem ipsum dolor sit amet.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;

この時、#testにbackground-colorを指定していると
.boxの背景スライドショーが表示されなくなってしまうのですが、
回避する方法はございますか。
&lt;body&gt;へbackground-color指定する場合は問題なく動作致します。

**Comment by rewish** [comment]
実際にスライドショーを行っている要素が `position: absolute; z-index: -1` で置かれているので、
#testに対して `position: relative; z-index: 0;` をあてることで解決するかも知れません。

**Comment by trickstar13** [comment]
ご提案頂きましたCSS指定にて解決致しました。
誠にありがとうございます。
