### ISSUE TITLE
Chrome issue

### ISSUE THREAD

**Issue by vinibrown** [rewish/jquery-bgswitcher#2]
Thanks for your jquery! good stuff!
I have a doubt... on chrome, images seem to just move right a bit just before the fade transition. So you have an idea of how to fix it?

**Comment by rewish** [comment]
I want an example code.

**Comment by vinibrown** [comment]
Hi!
the code i'm using is:
$(document).ready(function () {
    $(".wrapper").bgswitcher({
      images: ["img/carers-do-color.jpg", "img/nurses-do-color.jpg", "img/we-all-do.jpg"], // Background images
      effect: "fade", // fade, blind, clip, slide, drop, hide
      interval: 5000, // Interval of switching
      loop: false, // Loop the switching
      shuffle: false, // Shuffle the order of an images
      duration: 800, // Effect duration
      easing: "swing", // Effect easing
      position: "center top"
    });
});

you can check on this url: 
http://vartioli.com/clients/who
thanks!

**Comment by rewish** [comment]
Thank you for present an example!
I've removed margin of the switchable element.

Try it! 
https://raw.github.com/rewish/jquery-bgswitcher/0.4.1-dev/jquery.bgswitcher.js

**Comment by vinibrown** [comment]
This solved the issue!
thank you very much!
Great jquery!!!!
:-)
