### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by crecorn** [rewish/jquery-bgswitcher#20]
I saw your answer in your closed issues. Where does this go to make it responsive?

"CSS = Background-size: cover / contain"

**Comment by rewish** [comment]
Apply `background-size` CSS property to a background element.

Example for `contain`:

``` html
<div class="bg" style="background-size: contain;"></div>

<script>
$('.bg').bgswitcher({ images: ['1.jpg','2.jpg'] })
</script>
```

http://www.w3.org/TR/css3-background/#background-size

**Comment by rewish** [comment]
@crecorn Did you solve?
