### ISSUE TITLE
Console Issue from jquery.bgswitcher.js:232

### ISSUE THREAD

**Issue by sethsi2581** [rewish/jquery-bgswitcher#21]
Hi, 
I am a bit new to web design so I apologize in advance if there is a quick fix to this. 

I believe that all of my code is correct, and so far my initial image is being called in, but the transition to my additional images is not happening.

In the console, I get this:  "Uncaught TypeError: undefined is not a function"

```
/**
 * Switching the background image
 */
switching: function() {
  var started = !!this._timerID;

  if (started) {
    this.stop();
  }

  this._createSwitchableElement();
  this._prepareSwitching();

  this.switchHandler(this.$switchable);
```

/\* The error is marked on this line of code ^ */

```
  if (started) {
    this.start();
  }
},
```

Thanks!

**Comment by rewish** [comment]
Please show me the code of initialization.

**Comment by sethsi2581** [comment]
HTML -->

![screen shot 2014-11-23 at 12 35 30 pm](https://cloud.githubusercontent.com/assets/9909754/5158501/3d213074-730d-11e4-8909-a7eacbfe8ab6.png)

JQuery -->

$(".top").bgswitcher({
            images: ["background/girls.jpg", "background/fence.jpg", "background/work.jpg", "background/painting.jpg"],
            effect: "extraSlide"
        });

$.BgSwitcher.defineEffect("extraSlide", function($el) {
            $el.animate({right: -$el.width()}, 3000, fade);
        });

**Comment by rewish** [comment]
Please trying to initialize after `defineEffect`.

And, I'm sorry to have broken example code X(
Replace the CSS property from `right` to `left`:

``` js
$el.animate({left: $el.width()}, 3000, fade);
```

Thanks.
