### ISSUE TITLE
background attachment & position

### ISSUE THREAD

**Issue by twentyfortysix** [rewish/jquery-bgswitcher#22]
Hello

What I think the parameters are missing is the background position, which is absolute now making the background scrollable. 
And the background position is also always top left 0 0 which is also not always wanted.

thanks

**Comment by rewish** [comment]
Do you have an example code or page?

**Comment by twentyfortysix** [comment]
http://districtproductions.tv/wp/
(really temporary link)
I have hacked the position to fixed. If you reduce the width of a window you'll se how the picture might be better positioned on center.. or I see it this way.

**Comment by rewish** [comment]
Okay, specify the `background-position` to the body element.

**Comment by twentyfortysix** [comment]
nice ;)

**Comment by twentyfortysix** [comment]
..wait a second.. I tried that before.. and it doesn't work.. it works now without changes of the bgswitcher...
What a wizard tricks you have?

**Comment by rewish** [comment]
:stuck_out_tongue_closed_eyes:
