### ISSUE TITLE
Pause and seek to image index

### ISSUE THREAD

**Issue by radeno** [rewish/jquery-bgswitcher#3]
Hi,

this module is magnificant, and not lying :)

I using jQuery Backstretch, which is too good, but it uses img tag istead css background, and its deformed background on iOS and Adnroid tablet.

But that module have great thing like pause and seek to image on index position.

Do you plan to add something like that? Pause could be simulate with stop and play. But seeking not.

Regards!

**Comment by rewish** [comment]
Currently have no plans to implement, but Pull Request are welcome :)

Thanks!
