### ISSUE TITLE
Switch to slide x

### ISSUE THREAD

**Issue by stephenway** [rewish/jquery-bgswitcher#4]
Is there a way to setup a button to goto a specific slide?

**Comment by rewish** [comment]
Added new feature for select the slide x.
https://raw.github.com/rewish/jquery-bgswitcher/0.4.2-dev/jquery.bgswitcher.js

After initializing the BgSwitcher, you can be specified as follows:

``` js
$el.bgswitcher("select", index);
```

Example with button:

``` js
var $el = $(".box").bgswitcher({
  images: ["foo.jpg", "bar.jpg", "baz.jpg"]
});

$("button").on("click", function() {
  $el.bgswitcher("select", 1); // bar.jpg
});
```

Thanks!

**Comment by stephenway** [comment]
Thanks man, works like a charm!

**Comment by rewish** [comment]
Released new version with new feature!
Thank you for good idea :)
