### ISSUE TITLE
質問です

### ISSUE THREAD

**Issue by womoon** [rewish/jquery-bgswitcher#5]
とても使いたいのですが、うまく設定できません。

長いページの下部にあるdivまでスクロールしたときに、1度だけ背景を切り替えたいのですが、どのようにせっていすればいいのでしょうか？

お忙しいところ恐れ入りますが、ご回答よろしくお願いいたします。

**Comment by rewish** [comment]
大変申し訳ないですが、こちらでは個別のサポートは行っていません。
