### ISSUE TITLE
Transition on Chrome iOS

### ISSUE THREAD

**Issue by fr3dgentil** [rewish/jquery-bgswitcher#6]
There is a little bug with the transition on Chrome iOS.

**Comment by rewish** [comment]
Do you have an example?

**Comment by rewish** [comment]
I will close it

**Comment by jasonbahl** [comment]
I'm having the same issue. 

The transition seems to work fine on Safari for iOS but there's a Black blink in Chrome for iOS. 

Using the current version of Safari on both iPad and iPhone 6 and using Chrome version 39.0.2171.50 on iPad and iPhone 6. 

You can see an example on a site I'm working on here: http://lbhrenovations.staging.wpengine.com/galleries/kitchens/
