### ISSUE TITLE
Pre-Loading Images

### ISSUE THREAD

**Issue by slaterino** [rewish/jquery-bgswitcher#7]
I've looked through the code for bgSwitcher and saw that there is a preLoad function for the images. However, on my site there is often a jump between slides on the first load (i.e. before the images are cached) where the background goes white.

Here's the page: http://www.thgcreative.co.uk/senzala/

Is this related to the preLoad funciton? And if so, does this mean the preLoad function isn't working properly?

Thanks,
Russ

**Comment by rewish** [comment]
I'm sorry for the late reply.
Display of the image that has been preloaded, depends on the cache settings of the browser and server.

**Comment by rewish** [comment]
I'll close it.

**Comment by SgtPooki** [comment]
Experiencing this white flash issue in safari but no other browser.
