### ISSUE TITLE
Blink系ブラウザでのイージング不具合について

### ISSUE THREAD

**Issue by oceancrawler** [rewish/jquery-bgswitcher#8]
Demoを拝見したのですが、Blink系のブラウザでは画像切り替え時に一瞬画像が消える不具合が出ております。

対処法などございませんでしょうか？

↓ちなみにこのサイトにある古いバージョンのDemoはシームレスな切り替えができているようです。
http://www.jqueryscript.net/demo/Lightweight-jQuery-Background-Slideshow-Plugin-BgSwitcher/demo/

ちなみにIE11ではこの問題は発生しませんでした。

宜しくお願いいたします。

**Comment by rewish** [comment]
返事が遅くなりすみません。
画像の表示については、サーバやブラウザの設定次第でそのようになる場合があるみたいです。
ちなみに不具合が発生するのは http://rewish.github.io/jquery-bgswitcher/ こちらのデモページでしょうか？
